### ISSUE TITLE
Footer Text

### ISSUE THREAD

**Issue by cyouh95** [SymoneA/WareHouse-Capstone#2]
It may be a good idea to distinguish the footer headings (`Get to know us`, `Make money with us`, `Help`) a bit more from the list of links below. For example, you could use a slightly different color for the links:

```css
footer a {
  color: lightgray;
}
```
https://github.com/SymoneA/WareHouse-Capstone/blob/master/resources/css/base.css#L342-L344

And/or add a bit of spacing after the headings:
```css
footer h4 {
  margin-bottom: 10px;
}
```
https://github.com/SymoneA/WareHouse-Capstone/blob/master/resources/css/base.css#L337-L340
